## Taps
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
## General
brew "rclone"
brew "gping"
brew "qrencode"
cask "rectangle"
## Dev
brew "ansible"
brew "gnupg"
brew "go"
brew "hey"
cask "docker"
cask "postman"
cask "sourcetree"
cask "visual-studio-code"
